### ISSUE TITLE
[Windows 11] Some methods of UI Automation can not work in windows 11

### ISSUE THREAD

**Issue by kidmtt94** [microsoft/Microsoft-UI-UIAutomation#98]
Hi,

Related to UI Automation, I had used the following API and it work normally in Windows 10

```TreeWalker.RawViewWalker.getFirstChild(AutomationElemement)```

Unfortunately, when I upgraded windows from 10 to windows 11, it could not work normally like before. And it throws the following exception:
```
exception at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
[2364] at MS.Internal.Automation.UiaCoreApi.CheckError(Int32 hr)
[2364] at MS.Internal.Automation.UiaCoreApi.UiaNavigate(SafeNodeHandle hnode, NavigateDirection direction, Condition condition, UiaCacheRequest request)
[2364] at System.Windows.Automation.TreeWalker.GetFirstChild(AutomationElement element)
```
I had checked type of this exception and the result is ArgumentException. And the message of exception is "Not Implemented"

<b>Notes</b>: not only above API, some APIs of ```AutomationElement``` like GetCurrentPropertyValue,... has the same issue and all of them throws same exception ```Not Implemented```

OS Information:

Name: Microsoft Windows 11 Pro

Version 21H2 (OS Build 22000.795)

Could you let know that AutomationClient library officially support in Windows 11 yet ?
Please help me and let me know how to resolve this exception.

Thanks,

Will

**Comment by kamb1mca** [comment]
Same issue ... any updates on this

**Comment by pravinkharawade** [comment]
Same issue. Any updates on this issue.

**Comment by himanshukat05** [comment]
@pravinkharawade Windows apps like narrator and accessibility insights heavily used these APIs. Do you have any sample code or app for investigation?
